### ISSUE TITLE
Implement MyDevice* my_parse(string svg)

### ISSUE THREAD

**Issue by eliabonte** [eliabonte/Assignment1#17]
function, which creates a struct from a SVG textual representation

**Comment by eliabonte** [comment]
@DavidLeoni per questa funzione è possibile utilizzare librerie esterne? Cercando delle possibili soluzioni ho trovato che per ricercare stringhe in file di tipo xml si potrebbe farlo abbastanza facilmente con questa libreria qui: https://github.com/leethomason/tinyxml2/blob/master/tinyxml2.h
Posso procedere in questo modo?

**Comment by DavidLeoni** [comment]
cit.:    DO NOT use an SVG / XML library to write/load files

**Comment by eliabonte** [comment]
Ok, nel leggere la consegna me l'ero perso, Grazie
