### ISSUE TITLE
Approvazione device

### ISSUE THREAD

**Issue by eliabonte** [eliabonte/Assignment1#2]
@DavidLeoni Può andare bene come idea? Nel readme ho messo un prototipo. Ho pensato a un carrello di una gru che può spostarsi orizzontalmente, l'asta può ruotare e all'asta è attaccata una piattaforma (porta oggetti).
Guardando poi tra i device degli altri ho visto che un mio collega ha fatto una macchina quindi pensavo come "machine" di mettere la macchina sulla mia piattaforma.

**Comment by DavidLeoni** [comment]
Sì va bene

**Comment by eliabonte** [comment]
Approved
