### ISSUE TITLE
create a machine (eb_init_machine)

### ISSUE THREAD

**Issue by eliabonte** [eliabonte/Assignment1#34]
@DavidLeoni ho visto la mail con i consigli per l'integrazione di più device.  Stavo pensando di creare una struct machine con parametri relativi alla machine e con anche due array dinamici di puntatori alle struct dei due device che voglio mettere insieme.
Come di seguito:

struct MyMachine{
          int parametro1,
          int parametro2,
         MyDevice1** arr1,
         MyDevice2** arr2;
}

Può avere senso fare in questo modo?

**Comment by DavidLeoni** [comment]
sì
